endo/urls.py
from django.urls import path
from . import views

app_name = 'endo'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/admit', views.AdmitView.as_view(), name='admit'),
    path('create', views.create, name='create'),
    path('listinput', views.listinput, name='listinput'),
    path('result', views.result, name='result'),
    #path('results/', views.ReslutsView.as_view(), name='results'),

]

epiphora/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('endo/', include('endo.urls')),
    path('admin/', admin.site.urls),
]

endo/models.py
from django.db import models
import datetime
from separatedvaluesfield.models import SeparatedValuesField

# Create your models here.

class Constants():
    MALE = "M"
    FEMALE = "F"
    SEX_IN_CHOICE = (
        (MALE, "남자"),
        (FEMALE, "여자"),
    )


    OBST_TOTAL = "TO"
    OBST_PARTIAL = "PO"
    PASSAGE = "PA"
    UNKNOWN = "UK"

    RESULT_IN_SYR = ((OBST_TOTAL, "완전폐쇄"),
                     (OBST_PARTIAL, "불롼전폐쇄"),
                     (PASSAGE, "개통"),
                     (UNKNOWN, "미상 또는 자유기술"),
                     )

    G1 = "G1"
    G2 = "G2"
    G3 = "G3"
    G4 = "G4"
    RESULT_IN_EXAM_CHOICE = ((G1,'Grade1'),
                             (G2, "Grade2"),
                             (G3, "Grade3"),
                             (G4, "Grade4"),
                             )

    UPPER_CANAL = "UC"
    LOWER_CANAL = "LC"
    COMMON_CANAL = "CC"
    SAC = "SAC"
    KRAUSE = "KR"
    NLD = "NLD"
    UNKNOWN = "UK"
    RESULT_OBST_LOC_CHOICE = ((UPPER_CANAL, "상부누소관"),
                              (LOWER_CANAL, "하부누소관"),
                              (COMMON_CANAL, "Rosenmuller valve"),
                              (SAC, "sac"),
                              (KRAUSE,'krause valve'),
                              (NLD, "nasolacrimal duct"),
                              (UNKNOWN, "미상, 또는 자유기술"),
                              )
    MUCUS  = "muc"
    STONE = "stone"
    GRANULOMA = "gra"
    STENOSIS = "steno"
    FIBROSIS = "fibro"
    UNKNOWN = "UK"
    RESULT_OBST_CAUSE_CHOICE = ((MUCUS, "점액질"),
                                (STONE, "누석"),
                                (GRANULOMA, "육아종"),
                                (STENOSIS, "협착"),
                                (FIBROSIS, "섬유화"),
                                (UNKNOWN, "미상, 또는 정상"))




class Patient(models.Model):
    name = models.CharField(max_length=200)
    sex = models.CharField(max_length=1,
                           choices=Constants.SEX_IN_CHOICE,
                           null = True)
    birthday = models.DateField('생년월일', null=True)

    def __str__(self):
        return self.name


class BasicExam(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE, null=True)

    exam_date = models.DateField('검사일', null=True)

    tmh_rt = models.CharField("TMH 우안", max_length=8,
                              choices=Constants.RESULT_IN_EXAM_CHOICE,
                              default=Constants.G1,
                              )

    tmh_lt = models.CharField("TMH 좌안", max_length=8,
                              choices=Constants.RESULT_IN_EXAM_CHOICE,
                              default=Constants.G1,
                              )
    ddt_rt = models.CharField("DDT 우안", max_length=8,
                              choices=Constants.RESULT_IN_EXAM_CHOICE,
                              default=Constants.G1,
                              )
    ddt_lt = models.CharField("DDT 좌안", max_length=8,
                              choices=Constants.RESULT_IN_EXAM_CHOICE,
                              default=Constants.G1,
                              )


class Syr(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE, null=True)

    exam_date = models.DateField("검사일", null=True)


    syringe_rt = models.CharField("관류검사 우안", max_length=200,
                               choices=Constants.RESULT_IN_SYR,
                               default=Constants.PASSAGE,
                               )
    syringe_lt = models.CharField("관류검사 좌안", max_length=200,
                               choices=Constants.RESULT_IN_SYR,
                               default=Constants.PASSAGE,
                               )



class Dcg(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE, null=True)
    exam_date = models.DateField("검사일", null=True)
    obst_loc_rt = SeparatedValuesField("DCG 우안 폐쇄부위",
                                  choices=Constants.RESULT_OBST_LOC_CHOICE,
                                  max_length=100,
                                  null=True
                                       )
    obst_loc_lt = SeparatedValuesField("DCG 좌안 폐쇄부위", max_length=200,
                                  choices=Constants.RESULT_OBST_LOC_CHOICE,
                                   null=True
                                  )
    obst_cau_rt = SeparatedValuesField("DCG 우안 폐쇄원인", max_length=200,
                                  choices=Constants.RESULT_OBST_CAUSE_CHOICE,
                                       null=True)
    obst_cau_lt = SeparatedValuesField("DCG 우안 폐쇄원인", max_length=200,
                                  choices=Constants.RESULT_OBST_CAUSE_CHOICE,
                                  null=True)


class Dacryoscopy(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE, null=True)
    exam_date = models.DateField("검사일", null=True)
    obst_loc_rt = SeparatedValuesField("내시경 우안 폐쇄부위",
                                  choices=Constants.RESULT_OBST_LOC_CHOICE,
                                  max_length=100, null=True)
    obst_loc_lt = SeparatedValuesField("내시경 좌안 폐쇄부위", max_length=200,
                                  choices=Constants.RESULT_OBST_LOC_CHOICE,
                                       null=True)
    # obst_cau_rt = SeparatedValuesField("내시경 우안 폐쇄원인", max_length=200,
    #                               choices=Constants.RESULT_OBST_CAUSE_CHOICE,
    #                               )
    # obst_cau_lt = SeparatedValuesField("내시경 우안 폐쇄원인", max_length=200,
    #                               choices=Constants.RESULT_OBST_CAUSE_CHOICE,
    #                               )


class ObsCause(models.Model):
    dacryoscopy = models.ForeignKey(Dacryoscopy, on_delete=models.CASCADE, null=True)

    laterality = models.CharField(max_length=1,
                                  choices=(("R","우"),("L","좌")),
                                  default="R"
                                )

    mucus = models.BooleanField('점액질')
    stone = models.BooleanField('누석')
    granuloma = models.BooleanField('육아종')
    stenosis = models.BooleanField('협착')
    fibrosis = models. BooleanField('섬유화')
    unknown = models.BooleanField('미상/기타')

endo/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views import generic
from django.http import HttpResponseRedirect

from django.db.models import Max, Min, Count

from .models import *

# Create your views here.
class IndexView(generic.ListView):
    template_name = "endo/index.html"
    model = Patient


class DetailView(generic.DetailView):
    model = Patient
    template_name = "endo/detail.html"


class ResultView(generic.DetailView):
    model = Patient
    template_name = "endo/result.html"


class AdmitView(generic.DetailView):
    model = Patient
    template_name = "endo/admit.html"


def create(request):
    patient_p = Patient.objects.create(name= request.POST['name'],
                                       sex=request.POST['sex'],
                                       birthday=request.POST['birthday'])
    try:
        patient_p.save()
    except:
        return render(request, 'endo/listinput.html', { 'error_message': "You made a mistake.",})
    else:

        return HttpResponseRedirect(reverse('endo:index'))


def listinput(request):
    return render(request, "endo/listinput.html")


def result(request):
    a = {}
    a["maxage"] = Patient.objects.all().aggregate(Max('birthday'))["birthday__max"]
    a["minage"] = Patient.objects.all().aggregate(Min('birthday'))["birthday__min"]
    a["count"] = Patient.objects.count()
    return render(request, "endo/result.html", a)

endo/templates/endo/admit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

{{ patient }}

<form action = "{% url 'endo:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <input type ="radio" name="choice" id ="choice{{ forloop.counter }}" value = "{{ choice.id }}"/>
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
    {% endfor %}
    <input type="submit" value = "Vote"/>
</form>

</body>
</html>

endo/templates/endo/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>{{ patient.name }}</h1>


<ul>
    {% for exam in patient.basicexam_set.all %}
        <li>{{ exam.exam_date }} </li>
    {% endfor %}
</ul>
    <a href="{% url 'endo:admit' patient.id %}"> 수정 </a>




</body>
</html>

endo/templates/endo/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% if patient_list %}
    <ul>
        {% for patient in patient_list %}
            <li><a href="{% url 'endo:detail' patient.id %}"> {{ patient.name }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

<a href = "{% url 'endo:listinput' %}"> 환자 생성 </a>

</body>
</html>

endo/templates/endo/listinput.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

{% if error_message %}<p><strong> {{ error_message }}</strong></p>{% endif %}

<form action = "{% url 'endo:create'  %}" method="post">
    {% csrf_token %}
    <label for="name">이름 </label>
    <input type ="text" name="name" id = "name" /><br/>

    <label > <input type ="radio" name="sex" value="M"  />남</label>
    <label><input type ="radio" name="sex" value="F"  />여 </label>

    <label>생년월일 <input type="date" name="birthday" /> </label>


    <input type="submit" value = "create"/>
</form>


</body>
</html>

endo/templates/endo/result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<h3>환자 연령대 </h3>
{{ minage | timesince}}--{{maxage | timesince}}
<h3>환자 수 </h3>
{{count}}
<h3>DCG와 dacryoscopy  폐쇄위치 일치도 </h3>
{{kappa}}


</body>
</html>